version: "3.7"

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: docker
      MONGO_INITDB_ROOT_PASSWORD: mongopw
      MONGO_INITDB_DATABASE: own-blockchain
    ports:
      - "55000:27017"
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/*.js:ro
      - mongodb_server_data:/data/db
  
  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      
  miner-discovery:
    image: navin3d/miner-discovery
    ports:
      - "8010:8010"
    restart: "always"
  
  miner-orderer:
    build:
      context: ./miner/miner_orderer_peer
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: "always"
    depends_on:
      - miner-discovery
    environment:
      PORT: "8000"
      HOST: "miner-orderer"
      EUREKA_HOST: "miner-discovery"
      EUREKA_PORT: 8010
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
  
volumes:
  mongodb_server_data:
